### PR TITLE
Default request empty array value.

### PR DESCRIPTION
**Pull request by michael-molchanov**
To avoid 

count(): Parameter must be an array or an object that implements Countable

in remain method. Count function can't count NULLvalue.

### CODE REVIEW

**Comment by michael-molchanov** [comment]
Please review ASAP

**Comment by siliconmeadow** [comment]
I am in no way an expert in composer, but I saw the problem when setting up a Drupal project when I issued the following command earlier this evening:

```
composer create-project drupal-composer/drupal-project:8.x-dev scratch --stability dev --no-interaction
```

gave the error listed above.

I manually applied the patch and all seems to work.

**Comment by sunlix** [comment]
Got this error on my Drupal update due to the update of drupal-scaffold 2.5.
After adding this easy fix to my globally installed prestissimo it works again. :)
I think this fix can be applied fast. It would be nice, to be back on track again.

**Comment by siliconmeadow** [comment]
I agree - the more test coverage the better. Or maybe both PRs get merged, so you both get credit for the fix. ;-)

See my comment on the latter re: assertions.

**Comment by siliconmeadow** [comment]
Oh, wait. I see. #155 had already been merged.

**Comment by BR0kEN-** [comment]
That's not a PR 😆

**Comment by hirak** [comment]
I merged #173. Because there is a test, I thought it was better. I will make a release later. Thanks.

**Pull request closed without merging**
