### PR TITLE
#155: Missing PHP 7.2 support

### PR DESCRIPTION
**Pull request by BR0kEN-**
https://github.com/hirak/prestissimo/issues/155

### CODE REVIEW

**Comment by BR0kEN-** [comment]
Here it is - https://travis-ci.org/hirak/prestissimo/jobs/387040415, the issue with PHP 7.2.

**Comment by siliconmeadow** [comment]
Do you need to specify some asserts? I'm not a unit testing expert by the way...

**Comment by BR0kEN-** [comment]
@siliconmeadow, we don't since any notice/warning/exception - tests failures.

**Comment by NickWilde1990** [comment]
I can confirm this fixes 
[ErrorException]
  count(): Parameter must be an array or an object that implements Countable

In my case, this was caused by:
Script DrupalComposer\DrupalScaffold\Plugin::scaffold, but could happen with any, just including for future searcher

**Comment by juampynr** [comment]
Worked for me too. I was experiencing this error on `composer update drupal/core`:

```
Writing lock file
Generating autoload files
  [merge-plugin] Already merged web/modules/custom/ls_taxonomy/composer.json completely
  - Downloading 1/16: https://cgit.drupalcode.org/drupal/plain/sites/development.services.yml
  - Downloading 3/16: https://cgit.drupalcode.org/drupal/plain/sites/example.settings.local.php
  - Downloading 3/16: https://cgit.drupalcode.org/drupal/plain/robots.txt
  - Downloading 4/16: https://cgit.drupalcode.org/drupal/plain/sites/default/default.settings.php
  - Downloading 5/16: https://cgit.drupalcode.org/drupal/plain/sites/default/default.services.yml
  - Downloading 7/16: https://cgit.drupalcode.org/drupal/plain/sites/example.sites.php
  - Downloading 7/16: https://cgit.drupalcode.org/drupal/plain/index.php
  - Downloading 9/16: https://cgit.drupalcode.org/drupal/plain/web.config
  - Downloading 9/16: https://cgit.drupalcode.org/drupal/plain/.htaccess
  - Downloading 11/16: https://cgit.drupalcode.org/drupal/plain/.ht.router.php
  - Downloading 11/16: https://cgit.drupalcode.org/drupal/plain/.eslintrc.json
  - Downloading 13/16: https://cgit.drupalcode.org/drupal/plain/update.php
  - Downloading 13/16: https://cgit.drupalcode.org/drupal/plain/.gitattributes
  - Downloading 14/16: https://cgit.drupalcode.org/drupal/plain/.editorconfig
  - Downloading 15/16: https://cgit.drupalcode.org/drupal/plain/.eslintignore
  - Downloading 16/16: https://cgit.drupalcode.org/drupal/plain/.csslintrc

                                                                              
  [ErrorException]                                                            
  count(): Parameter must be an array or an object that implements Countable  
                                                                              

Exception trace:
 () at /home/juampy/.composer/vendor/hirak/prestissimo/src/CurlMulti.php:156
```

**Comment by hirak** [comment]
thanks!

**Comment by BR0kEN-** [comment]
Thanks for merging! Let's create a release, please.

**Pull request merged**
