### PR TITLE
Drop STDOUT

### LINKED ISSUE #77: STDOUT usage
I'm using Composer in somehow interesting way.
Long story short: it works under mod_php/php-fpm, not in CLI mode.
But with this plugin it causes an issue:
```
  [ErrorException]                                     
  Use of undefined constant STDOUT - assumed 'STDOUT'  
                                                       

Exception trace:
 () at /web/cscms.org/www/storage/Composer/tmp/vendor/hirak/prestissimo/src/CurlRemoteFilesystem.php:77
 Composer\Util\ErrorHandler::handle() at /web/cscms.org/www/storage/Composer/tmp/vendor/hirak/prestissimo/src/CurlRemoteFilesystem.php:77
 Hirak\Prestissimo\CurlRemoteFilesystem->Hirak\Prestissimo\{closure}() at /web/cscms.org/www/storage/Composer/tmp/vendor/hirak/prestissimo/src/CurlRemoteFilesystem.php:146
 Hirak\Prestissimo\CurlRemoteFilesystem->fetch() at /web/cscms.org/www/storage/Composer/tmp/vendor/hirak/prestissimo/src/CurlRemoteFilesystem.php:84
 Hirak\Prestissimo\CurlRemoteFilesystem->copy() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Downloader/FileDownloader.php:139
 Composer\Downloader\FileDownloader->doDownload() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Downloader/FileDownloader.php:91
 Composer\Downloader\FileDownloader->download() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:36
 Composer\Downloader\ArchiveDownloader->download() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Downloader/ZipDownloader.php:65
 Composer\Downloader\ZipDownloader->download() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:176
 Composer\Installer\LibraryInstaller->installCode() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer/PluginInstaller.php:61
 Composer\Installer\PluginInstaller->install() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer.php:568
 Composer\Installer->doInstall() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Console/Application.php:181
 Composer\Console\Application->doRun() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///web/cscms.org/www/components/modules/Composer/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at /web/cscms.org/www/components/modules/Composer/Composer.php:127
```

Can you get rid of using STDOUT directly or use something else if it is not available? Composer itself provides an abstraction on top of that using Symfony's components, maybe you can use it?

### PR DESCRIPTION
**Pull request by hirak**
fixed #77

### CODE REVIEW

**Comment by teohhanhui** [comment]
This caused:

```
curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*
```

**Comment by bgaillard** [comment]
Hi, we also encounter the following error.

```
PS C:\workspace\xxx-administration\src\main\php\zf2> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Prefetch start: total: 4


  [ErrorException]
  curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimi
ze-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by teohhanhui** [comment]
@bgaillard It's already been fixed by #88

**Comment by bgaillard** [comment]
@teohhanhui :+1: great ! 

So waiting for this fix to be integrated in the next version :).

Thanks

**Pull request merged**
